/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projet.approche.objet;

//import projet.approche.objet.domain.*;
import projet.approche.objet.domain.valueObject.game.GameStarter;
import projet.approche.objet.domain.valueObject.game.exceptions.GameAlreadyStarted;
import projet.approche.objet.domain.valueObject.game.exceptions.GameEnded;
import projet.approche.objet.domain.valueObject.game.exceptions.GameNotStarted;
import projet.approche.objet.domain.valueObject.resource.Resource;
import projet.approche.objet.domain.aggregates.*;
import projet.approche.objet.domain.entities.building.Building;
import projet.approche.objet.domain.valueObject.building.BuildingList;
import projet.approche.objet.domain.valueObject.building.BuildingType;

import java.util.Scanner;
import java.io.Console;

public class App {
	public String getGreeting() {
		return "Welcome !!!";
	}

	public static void main(String[] args) throws GameNotStarted, GameAlreadyStarted, GameEnded {


	}
}
